FROM fedora:28
LABEL maintainer="Factory 2.0"

WORKDIR /src
# TODO: Replace the Koji URL once the following is stable https://bodhi.fedoraproject.org/updates/FEDORA-2018-c929a49b1b
RUN dnf -y install \
    --setopt=deltarpm=0 \
    --setopt=install_weak_deps=false \
    --setopt=tsflags=nodocs \
    bash \
    python3-flask \
    https://kojipkgs.fedoraproject.org/packages/python-flask-oidc/1.4.0/1.fc28/noarch/python3-flask-oidc-1.4.0-1.fc28.noarch.rpm \
    python3-gunicorn \
    python3-neomodel \
    python3-six \
    && dnf clean all
# This will allow a non-root user to install a custom root CA at run-time
RUN chmod 777 /etc/pki/tls/certs/ca-bundle.crt
COPY . .
# Install using develop so we can use the --no-deps options to ensure nothing comes from PyPi.
# Normally we'd use something like `pip3 install . --no-deps` but certain neomodel scripts must
# import estuary dynamically, and for whatever reason, that fails when this is installed using pip.
RUN python3 setup.py develop --no-deps --prefix /usr
USER 1001
CMD ["/usr/bin/bash", "-c", "docker/install-ca.sh && exec gunicorn-3 --bind 0.0.0.0:8080 --access-logfile=- --enable-stdio-inheritance estuary.wsgi:app"]
