FROM fedora:30

# TODO: Replace the Koji URL once the following is stable https://bodhi.fedoraproject.org/updates/FEDORA-2018-c929a49b1b
RUN dnf -y install \
  --setopt=deltarpm=0 \
  --setopt=install_weak_deps=false \
  --setopt=tsflags=nodocs \
  nmap-ncat \
  python3-devel \
  python3-flake8 \
  python3-flask \
  python3-flask-oidc \
  python3-ldap3 \
  python3-mock \
  python3-mypy \
  python3-neomodel \
  python3-prometheus_client \
  python3-pytest \
  python3-pytest-cov \
  python3-flake8-docstrings \
  && dnf clean all

VOLUME /src
WORKDIR /src
# Inspired from https://github.com/neo4j-contrib/neomodel/blob/master/tests-with-docker-compose.sh
CMD ["sh", "-c", "while ! nc -z -w 2 neo4j 7687; do sleep 1; done; pytest-3 -vvv --cov-report term-missing --cov=estuary --ignore=tests/functional tests && flake8 && mypy --ignore-missing-imports ."]
