FROM registry.access.redhat.com/ubi8/ubi-minimal

RUN microdnf -y install \
    bash \
    nmap-ncat \
    python3-pip \
    && microdnf clean all

COPY tests/requirements.txt /tmp/requirements.txt
VOLUME /src
WORKDIR /src
RUN pip3 install -r /tmp/requirements.txt --no-deps --require-hashes --prefix /usr
# Inspired from https://github.com/neo4j-contrib/neomodel/blob/master/tests-with-docker-compose.sh
CMD ["sh", "-c", "while ! nc -z -w 2 neo4j 7687; do sleep 1; done; pytest -vvv --cov-report term-missing --cov=estuary --ignore=tests/functional --ignore=tests/infra tests && mypy --ignore-missing-imports ."]
