FROM registry.access.redhat.com/ubi8/ubi-minimal
LABEL maintainer="Factory 2.0"

ENV SCRAPER=all \
    TEIID_USER=username \
    TEIID_PASSWORD=password \
    NEO4J_USER=neo4j \
    NEO4J_PASSWORD=neo4j \
    NEO4J_SERVER=neo4j \
    SCRAPE_FROM_DAYS_AGO=365 \
    WAIT_FOR=0

WORKDIR /src
RUN microdnf -y install \
    bash \
    gcc \
    libpq-devel \
    python3-devel \
    python3-pip \
    && microdnf clean all
# This will allow a non-root user to install a custom root CA at run-time
RUN chmod 777 /etc/pki/tls/certs/ca-bundle.crt
COPY . .
RUN pip3 install -r scraper-requirements.txt --no-deps --require-hashes --prefix /usr \
    && pip3 install . --no-deps --prefix /usr
USER 1001
CMD ["/usr/bin/bash", "-c", "docker/scrape.sh"]
