FROM fedora:28
LABEL maintainer="Factory 2.0"

ENV SCRAPER=all \
    TEIID_USER=username \
    TEIID_PASSWORD=password \
    NEO4J_USER=neo4j \
    NEO4J_PASSWORD=neo4j \
    NEO4J_SERVER=neo4j

WORKDIR /src
RUN dnf -y install \
    --setopt=deltarpm=0 \
    --setopt=install_weak_deps=false \
    --setopt=tsflags=nodocs \
    python3-beautifulsoup4 \
    python3-flask \
    python3-neomodel \
    python3-psycopg2 \
    python3-PyYAML \
    python3-requests \
    python3-six \
    && dnf clean all
# This will allow a non-root user to install a custom root CA at run-time
RUN chmod 777 /etc/pki/tls/certs/ca-bundle.crt
COPY . .
USER 1001
CMD ["bash", "docker/run-scrapers.sh"]
