# Inspired from https://github.com/neo4j-contrib/neomodel/blob/master/tests-with-docker-compose.sh
version: '3'
services:
  estuary_api_tests:
    build:
      context: ../
      dockerfile: docker/Dockerfile-tests
    volumes:
      - ../:/src:Z
    links:
      - neo4j
    environment:
      NEO4J_BOLT_URL: bolt://neo4j:neo4j@neo4j:7687
  neo4j:
    image: neo4j:3.5.26
    container_name: neo4j
    environment:
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4JLABS_PLUGINS: "[\"apoc\"]"
      NEO4J_AUTH: none
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_connector_bolt_enabled: "true"
      NEO4J_dbms_connector_bolt_listen__address: "0.0.0.0:7687"
