FROM registry.access.redhat.com/ubi8/ubi
LABEL maintainer="Factory 2.0"

RUN dnf -y install \
    --setopt=deltarpm=0 \
    --setopt=install_weak_deps=false \
    --setopt=tsflags=nodocs \
    bash \
    python3-pip \
    && dnf clean all
# This will allow a non-root user to install a custom root CA at run-time
RUN chmod 777 /etc/pki/tls/certs/ca-bundle.crt
WORKDIR /src
COPY . .
RUN pip3 install -r requirements.txt --no-deps --require-hashes --prefix /usr \
    && pip3 install . --no-deps --prefix /usr
USER 1001
CMD ["/usr/bin/bash", "-c", "docker/install-ca.sh && exec gunicorn --bind 0.0.0.0:8080 --access-logfile=- --enable-stdio-inheritance estuary.wsgi:app"]
