FROM fedora:28
LABEL maintainer="Factory 2.0"

ENV SCRAPER=all \
    TEIID_USER=username \
    TEIID_PASSWORD=password \
    NEO4J_USER=neo4j \
    NEO4J_PASSWORD=neo4j \
    NEO4J_SERVER=neo4j \
    SCRAPE_FROM_DAYS_AGO=730 \
    WAIT_FOR=0

WORKDIR /src
RUN dnf -y install \
    --setopt=deltarpm=0 \
    --setopt=install_weak_deps=false \
    --setopt=tsflags=nodocs \
    python3-beautifulsoup4 \
    python3-flask \
    # Until 1.6.0 is supported, we need to hardcode this entry
    python3-neo4j-driver-1.5.3 \
    python3-neomodel \
    python3-psycopg2 \
    python3-PyYAML \
    python3-requests \
    python3-six \
    && dnf clean all
# This will allow a non-root user to install a custom root CA at run-time
RUN chmod 777 /etc/pki/tls/certs/ca-bundle.crt
COPY . .
USER 1001
ENTRYPOINT docker/install-ca.sh && sleep $WAIT_FOR && exec python3 scripts/scrape.py $SCRAPER --teiid-user $TEIID_USER --teiid-password $TEIID_PASSWORD --neo4j-user $NEO4J_USER --neo4j-password $NEO4J_PASSWORD --neo4j-server $NEO4J_SERVER --days-ago $SCRAPE_FROM_DAYS_AGO
