apiVersion: v1
kind: Template
metadata:
  name: purview-scrapers-initial-run
parameters:
- name: NEO4J_SERVER
  displayName: NEO4J Server
  description: The FQDN or IP address to the Neo4j server
  value: neo4j
- name: CA_URL
  displayName: CA URL
  description: The URL to a custom CA to be trusted in the container
- name: SCRAPE_FROM_DAYS_AGO
  displayName: Scrape from x days ago
  description: The number of days ago to start scraping from
  value: "730"
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: purview-scrapers
  spec:
    parallelism: 1
    completions: 1
    template:         
      metadata:
        name: purview-scrapers
      spec:
        containers:
        - name: purview-scrapers
          image: quay.io/factory2/purview-scrapers:latest
          env:
          - name: TEIID_USER
            valueFrom:
              secretKeyRef:
                name: purview-scrapers-secret
                key: teiid_user
          - name: TEIID_PASSWORD
            valueFrom:
              secretKeyRef:
                name: purview-scrapers-secret
                key: teiid_password
          - name: NEO4J_USER
            valueFrom:
              secretKeyRef:
                name: purview-scrapers-secret
                key: neo4j_user
          - name: NEO4J_PASSWORD
            valueFrom:
              secretKeyRef:
                name: purview-scrapers-secret
                key: neo4j_password
          - name: NEO4J_SERVER
            value: "${NEO4J_SERVER}"
          - name: CA_URL
            value: "${CA_URL}"
          - name: SCRAPE_FROM_DAYS_AGO
            value: "${SCRAPE_FROM_DAYS_AGO}"
        restartPolicy: OnFailure
